#!/bin/sh
#
# Start the network....
#

start() {
	echo "Network starting ..."
	/bin/hostname -F /etc/hostname
#	/sbin/ifconfig eth0 hw ether 00:1F:F2:00:00:00
	/sbin/ifconfig lo 127.0.0.1 up
	/sbin/route add -net 127.0.0.0 netmask 255.0.0.0 lo
#	/sbin/ifconfig eth0 192.168.0.136 up
#	/sbin/route add default gw 192.168.0.1
#	/bin/sleep 1
}	
stop() {
	echo "Network stoping ..."
#	/sbin/ifconfig eth0 down
	/sbin/ifconfig lo down
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

#/usr/sbin/inetd &
#/usr/sbin/httpd -h /mnt/www/html &
