#!/bin/sh

start() {
	echo "Starting pppd ..."
	/usr/sbin/pppd-starter &
}	
stop() {
	echo "Stoping pppd ..."
	killall pppd-starter
	killall pppd
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

