#! /bin/sh
#
# submitted by Morgon Kanter
# 

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/sbin/vtund
CONFFILE=/etc/vtund.conf
PIDPREFIX=/var/run/vtund

test -f $DAEMON || exit 0
  
case "$1" in 
       start)
              echo  "Starting vtund client ...";
              start-stop-daemon --start --exec $DAEMON --pidfile $PIDPREFIX.pid -- spectrator difur.ru;
              ;;
       stop) 
          echo "Stopping vtund.";
          for i in $PIDPREFIX*;
          do
              start-stop-daemon --stop --pidfile $i; 
              rm -f $i;
          done
               ;;
       reload|force-reload)
          echo "Reloading vtund.";
          for i in $PIDPREFIX*;
          do
              start-stop-daemon --stop --signal 1 --pidfile $i; 
          done
              ;;
       restart) 
          $0 stop
          sleep 1;
          $0 start
          ;;
   *)
      echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
       exit 1
               ;;
esac
exit 0
