#!/bin/sh

start() {
	echo "Starting telnetd ..."
	/usr/sbin/telnetd -l /bin/sh
}	
stop() {
	echo "Stoping telnetd ..."
	killall telnetd
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

