#!/bin/sh

start() {
	echo "Starting ftpd ..."
	/usr/bin/tcpsvd -E -u root:root 0.0.0.0 21 ftpd -w / &
}	
stop() {
	echo "Stoping ftpd ..."
	#killall telnetd
}
restart() {
	stop
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

